<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
<ItemGroup>
<ProjectReference Include="../TempMail.Infrastructure/TempMail.Infrastructure.csproj" />
<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
</ItemGroup>
<ItemGroup><None Update="appsettings*.json" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
<ItemGroup><None Update="appsettings.Local.json" CopyToPublishDirectory="Never" /></ItemGroup>
</Project>